[features]
seeds = false
[programs.localnet]
tic_tac_toe = "6BzuJZBHQXM5H8diTy5Pj6E91NdKfwnJ6joCf6Y6RnXp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/fsodano/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
